name: CI + Safe Deploy to cPanel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint

  docker-build:
    name: Docker Build & Cache Push
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image with Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sarkar-group:latest
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sarkar-group:cache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/sarkar-group:cache,mode=max

  # cpanel-deploy:
  #   name: Build & Deploy to cPanel
  #   runs-on: ubuntu-latest
  #   needs: docker-build
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build Vite app
  #       run: npm run build

  #     - name: Upload dist folder to cPanel via FTP
  #       uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  #       with:
  #         server: ${{ secrets.FTP_HOST }}
  #         username: ${{ secrets.FTP_USERNAME }}
  #         password: ${{ secrets.FTP_PASSWORD }}
  #         local-dir: ./dist
  #         server-dir: ${{ secrets.FTP_TARGET }}
